meta:
  tmp_dir: "/path/to/DownloadingAndEncodingWorkDir"
  aria2c_cmd: "aria2c -s16 -x16 -k1M --seed-time=0 --file-allocation=none"
  ffmpeg_cmd: "ffmpeg -hide_banner"
  encoding_profiles:
    ## default values:
    ## - default: "-map 0 -c:v libsvtav1 -crf 32 -c:a aac -ac 2 -c:s copy"
    ## - original: null
    - av1: "-map 0 -c:v libsvtav1 -crf 32 -c:a aac -ac 2 -c:s copy"
  catalogs:
    tv:
      base_dir: "/path/to/tvs"
    movie:
      base_dir: "/path/to/movies"

# catalogs > series > episodes
# a episode will be download to {catalog.base_dir}/{series.title}/"{series.title} {episode.key}.{epidode.format}"
series:
  konoSubaS03:
    title: "Kono Subarashii Sekai ni Shukufuku wo"
    catalog: tv
    episodes:
      - key: S03E01
        source: "magnet:..."
        encoding: original|av1
        format: mp4|mkv
      - key: S03E01
        source: "magnet:..."
  monoS01:
    title: "mono"
    catalog: tv
    episodes:
      - key: S01E01
        source: "magnet:..."
  evaNT4:
    title: "Evangelion 3.0_1.01 Thrice Upon a Time"
    catalog: movie
    episodes:
      - key: "[1080p][en_US]"
        source: "magnet:..."
