_meta_:
  tmp_dir: "/path/to/DownloadingAndEncodingWorkDir"
  aria2c_cmd: "aria2c -s16 -x16 -k1M --seed-time=0 --file-allocation=none"
  ffmpeg_cmd: "ffmpeg -hide_banner"
  encoding_profiles:
    - av1: "-map 0 -c:v libsvtav1 -crf 32 -c:a aac -ac 2 -c:s copy"
    - original: null
  catalogs:
    tv:
      base_dir: "/path/to/tvs"
    movie:
      base_dir: "/path/to/movies"

# a episode will be download to {media.base_dir}/{media_entry.title}/"{media_entry.title} {episode.key}.{epidode.format}"
tv:
  konoSubaS03:
    title: "Kono Subarashii Sekai ni Shukufuku wo"
    episodes:
      - key: S03E01
        source: "magnet:..."
        encoding: original|av1
        format: mp4|mkv
      - key: S03E01
        source: "magnet:..."
  monoS01:
    title: "mono"
    episodes:
      - key: S01E01
        source: "magnet:..."

# movie is actaully the same to tv
movie:
  evaNT3:
    title: "Evangelion 3.0_1.01 Thrice Upon a Time"
    episodes:
      - key: "[1080p][en_US]"
        source: "magnet:..."
