meta:
  tmp_dir: "./work"
  aria2c_cmd: "aria2c -s16 -x16 -k1M --seed-time=0 --file-allocation=none --bt-min-crypto-level=arc4 --continue=true"
  ffmpeg_cmd: "ffmpeg -hide_banner"
  encoding_profiles:
    - av1: "-map 0 -c:v libsvtav1 -crf 32 -c:a aac -ac 2 -c:s copy"
    - original: null
  catalogs:
    tv:
      dir: "./bunting"
    movie:
      dir: "./bunting"

